### PR TITLE
Fix handling of deep multiparti variables, eg. VAR1%FIELD2%FIELD3

### PR DESCRIPTION
**Pull request by mlange05**
data_ref: Hoist `name` elements in a loop to fix handling of multipart variables (`numPartRef > 2`), such as `VAR1%FIELD2%FIELD3`. An example code to illustrate the effect is:

```
SUBROUTINE TEST_ASSOC(VAR1, VAR2)                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                
IMPLICIT NONE                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                
TYPE(SOME_TYPE)      , INTENT (INOUT) :: VAR1                                                                                                                                                                                                                                   
TYPE(SOME_OTHER_TYPE), INTENT (INOUT) :: VAR2                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                
ASSOCIATE(V1=>VAR1%FIELD1, V2=>VAR2%FIELD2%FIELD3)                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                
IF (VAR2%FIELD4%BOOL1 == 1) THEN                                                                                                                                                                                                                                                
   V1(:) = V2(:)                                                                                                                                                                                                                                                                
END IF                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                
END ASSOCIATE                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                
END SUBROUTINE TEST_ASSOC           
```

### CODE REVIEW

**Comment by mbdevpl** [comment]
Thanks a lot for the PR!

I was looking through your example, the fix is definitely valid.

I discovered however, that in such cases the resulting `id` gets quite mangled.

So your example `VAR2%FIELD4%BOOL1` becomes:

```xml
<name col_begin="4" col_end="21" hasSubscripts="false" id="id=&quot;VAR2&quot;%id=&quot;FIELD4&quot;%BOOL1" line_begin="10" line_end="10" type="ambiguous">
  <part-ref col_begin="4" col_end="8" hasImageSelector="false" hasSectionSubscriptList="false" id="VAR2" line_begin="10" line_end="10" rule="613"/>
  <part-ref col_begin="9" col_end="15" hasImageSelector="false" hasSectionSubscriptList="false" id="FIELD4" line_begin="10" line_end="10" rule="613"/>
  <part-ref col_begin="16" col_end="21" hasImageSelector="false" hasSectionSubscriptList="false" id="BOOL1" line_begin="10" line_end="10" rule="613"/>
  <data-ref numPartRef="3" rule="612"/>
  <designator-or-func-ref rule="-3"/>
  <primary rule="701"/>
</name>
```

The id is definitely wrong: `id="id=&quot;VAR2&quot;%id=&quot;FIELD4&quot;%BOOL1"`.

It's not the fault of your PR, but I will work on a fix before trying to merge your work.

**Comment by mlange05** [comment]
@mbdevpl Many thanks for looking into this so promptly. 

Yes, I had noticed the funny looking IDs, but thought I'd leave it for another PR. I'm happy to wait for your fix though.

Out of curiosity, would your ID fix also honor subscripts of the  individual sub-components? For example if we had something like `VAR1%FIELD(I,J)%BOOL1` in the source, what would the corresponding `id` attribute of the outer `<name>` element be? (Feel free to ignore; I'm really just curious what the intention here is.)

**Comment by mbdevpl** [comment]
Well, the `VAR2%FIELD2(42)%FIELD3` becomes:

```xml
<name col_begin="31" col_end="53" hasSubscripts="false" id="VAR2%FIELD2%FIELD3" line_begin="8" line_end="8" type="ambiguous">
  <part-ref col_begin="31" col_end="35" hasImageSelector="false" hasSectionSubscriptList="false" id="VAR2" line_begin="8" line_end="8" rule="613"/>
  <subscripts col_begin="43" col_end="45" count="1" line_begin="8" line_end="8">
    <section-subscript-list__begin addendum="list-begin" rule="619"/>
    <subscript col_begin="43" col_end="45" line_begin="8" line_end="8" type="simple">
      <literal col_begin="43" col_end="45" line_begin="8" line_end="8" type="int" value="42">
        <int-literal-constant col_begin="43" col_end="45" digitString="42" kindParam="" line_begin="8" line_end="8" rule="406"/>
        <literal-constant rule="306"/>
        <primary rule="701"/>
      </literal>
      <section-subscript hasLowerBound="true" hasStride="false" hasUpperBound="false" isAmbiguous="true" rule="619"/>
    </subscript>
    <section-subscript-list addendum="list" count="1" rule="619"/>
  </subscripts>
  <part-ref col_begin="36" col_end="42" hasImageSelector="false" hasSectionSubscriptList="true" id="FIELD2" line_begin="8" line_end="8" rule="613"/>
  <part-ref col_begin="47" col_end="53" hasImageSelector="false" hasSectionSubscriptList="false" id="FIELD3" line_begin="8" line_end="8" rule="613"/>
  <data-ref numPartRef="3" rule="612"/>
  <designator-or-func-ref rule="-3"/>
  <primary rule="701"/>
</name>
```

Which perfectly illustrates how limited and flawed is the handling of `something%something` even at the 1st nesting level.

I'm starting to think it would be better to reimplement it entirely so that each of `var1%var2%var3%var4` is a separate nested `<name>` (or even *new* `<component>`) node that can handle it's own `<subscripts>` and the nested `<name>`s without trouble.

This way also `id` woudn't be abused anymore in a very bad way, because the intent is for `id` to store a single name and just a name -- subscripts are already stored in their own separate nodes, and they too can be names and have their own subscripts, and so on.

For an example I'll use Python:

```python
import ast
import astunparse

syntax = ast.parse('a.b.c.d', mode='eval')
print(astunparse.dump(syntax))
```

```python
Expression(body=Attribute(
  value=Attribute(
    value=Attribute(
      value=Name(
        id='a',
        ctx=Load()),
      attr='b',
      ctx=Load()),
    attr='c',
    ctx=Load()),
  attr='d',
  ctx=Load()))
```

However, the thing is that in my work with Open Fortran Parser I'm not currently targetting the object-oriented side of modern Fortran, but rather compute kernels, in which used syntax is quite constrained.

BTW, several other syntactic features of modern Fortran are currently completely not handled.

So, in short, the derived type component access operator `%` is really not handled how it should be. I really wouldn't mind if you have a good idea for a proper implementation of such handling - but I have to admit that it's not so high on my list right now...

On the other hand, if I ever encounter it in some of the kernels I'm working with, I quess it could suddenly become high priority :)

**Comment by mbdevpl** [comment]
Ok, I've fixed the `id` mess and also merged this PR. I'm very open to more pull requests - if you have an idea how something should be improved, go ahead!

Just one comment, if you wanna automatically test if your fix works, you can put some minimalistic file in `test/examples/myfile.f90` directory - it will be automatically treated as a test case. This kind of testing is not very rigorous, because it would basically test if parser crashes or not.

But then, at least after you run tests on your own machine, you can inspect the corresponding file `test/results/examples/myfile.f90.xml` to check how exactly it was parsed.

To run the tests, I usually do
```bash
$ ant # only necessary after you change Java code
$ python3.6 -m unittest discover --verbose
```

You can also run `$ TEST_LONG=1 python3.6 -m unittest discover --verbose` -- that takes much longer but is more thorough, and that is what runs on Travis and Appveyor.

**Comment by mlange05** [comment]
> Ok, I've fixed the id mess and also merged this PR. I'm very open to more pull requests 

Many thanks, indeed, that was quick. I've submitted some more small improvements and bug fixes, and I still have a list of further things that I'm currently working around downstream, so expect more soon. :wink: 

> Just one comment, if you wanna automatically test if your fix works, you can put some minimalistic file in test/examples/myfile.f90 directory - it will be automatically treated as a test case. This kind of testing is not very rigorous, because it would basically test if parser crashes or not.

Thanks for the pointer. I've added a small test like this to PR #8 to illustrate the problem. As mentioned in the same PR, I've also had some vague thoughts on how to improve the testing a bit, but I've not yet had any time to look into this further. Hopefully I can find some time soon, as I'm relying on this parser quite heavily in my current project and would like it to be nice and stable. :smile:

**Pull request merged**
